
abstract=
ontologyTitle=ODRL Profile for clinical emergency access
ontologyPrefix=[Ontology NS Prefix]
ontologyNamespaceURI=https://w3id.org/btg/
ontologyName=ODRL Profile for clinical emergency access
thisVersionURI=null
latestVersionURI=
previousVersionURI=
dateCreated=
dateModified=
ontologyRevisionNumber=0.3.0
licenseURI=https://creativecommons.org/licenses/by/4.0/
licenseName=https://creativecommons.org/licenses/by/4.0/
licenseIconURL=null
citeAs=Juan Cano de Benito. ODRL Profile for clinical emergency access. Revision: 0.3.0.
DOI=
status=Ontology Specification Draft
logo=
description=
introduction=
backwardsCompatibleWith=
publisher=
publisherURI=
publisherInstitution=
publisherInstitutionURI=
authors=Juan Cano de Benito
authorsURI=
authorsInstitution=
authorsInstitutionURI=
contributors=
contributorsURI=
contributorsInstitution=
contributorsInstitutionURI=
importedOntologyNames=
importedOntologyURIs=
extendedOntologyNames=
extendedOntologyURIs=
RDFXMLSerialization=ontology.owl
TurtleSerialization=ontology.ttl
NTSerialization=ontology.nt
JSONLDSerialization=ontology.jsonld
images=
source=
seeAlso=https://www.w3.org/TR/odrl-model/
fundingGrants=
funders=
